add: exploration team page
availproject/availproject.github.io pull request #119
Opened 2023-10-06 18:41 UTC by swarna1101

#104

2023-10-06 21:17 UTC, DannyS03 requested changes
Thanks @swarna1101, I added various suggestions.

Another nit is to change the filename from "exploration" to "explorations"

2023-10-06 21:17 UTC, DannyS03 commented on docs/exploration.md
> +| Project              | Description | Repository |
The "Project" column contains repository names. We should improve this. 

We can either rename "Project" to "Repository" and remove the existing "Repository" column, or keep "Project" but rename each entry into a more formal project name, and then use the entries that currently exist under "Project" to replace the usage of "link" in each row with the actual repository name. I think I'd be in favor of the latter.

Example:

```
| Adapter for Sovereign SDK |  A data availability adapter for sovereign rollups integrated with the Sovereign SDK   | [sovereign-da-adapter](https://github.com/availproject/sovereign-sdk/tree/main) |

```

2023-10-06 21:17 UTC, DannyS03 commented on docs/exploration.md
> +
We should use this page to offer more of a breakdown of each "exploration".

So, we should address:
- What we mean by adapter (DA adapter)
- What we mean by interface (DA interface)
- In a statement or two, what each project is composed of

2023-10-06 21:17 UTC, DannyS03 commented on docusaurus.config.js
> +              href: '/category/exploration-team/',
I don't think this is part of a category in its current form

2023-10-06 21:17 UTC, DannyS03 commented on docusaurus.config.js
> +              label: 'Exploration Team',
```suggestion
              label: 'Data Availability Explorations',
```

2023-10-06 21:17 UTC, DannyS03 commented on docusaurus.config.js
> +  url: "https://availproject.github.io/",
we should not be changing this back

2023-10-06 21:17 UTC, DannyS03 commented on docs/exploration.md
> +id: exploration
```suggestion
id: explorations
```

2023-10-06 21:17 UTC, DannyS03 commented on sidebars.js
> +      type:"doc",
we just need to reference the doc's id like how the other id's are included

2023-10-06 21:17 UTC, DannyS03 commented on sidebars.js
> -    "index",
how come this is being removed?

2023-10-06 21:17 UTC, DannyS03 commented on sidebars.js
> +/**
All of this was previously deleted because it is unused

2023-10-10 17:35 UTC, DannyS03 commented on docs/exploration.md
> +
Not really addressed

2023-10-10 17:35 UTC, DannyS03 commented on sidebars.js
> +/**
Not addressed

2023-10-10 17:35 UTC, DannyS03 commented on sidebars.js
> -    "index",
Not addressed

2023-10-10 17:35 UTC, DannyS03 commented on sidebars.js
> +      type:"doc",
Not addressed

2023-10-10 19:04 UTC, swarna1101 commented on sidebars.js
> -    "index",
fixed in the latest commit

2023-10-14 09:57 UTC, DannyS03 requested changes
We still don't explain what we mean by adapter or interface. As proposed [here](https://github.com/availproject/availproject.github.io), let's include these terms as part of the glossary in another update and not let it be a blocker for this.

The statements on each project could probably be more compact and all need to be improved for writing style. There should also be some consistency in the form they are presented in. However, the idea is to explain the project (i.e, exploration), and not just the specific stacks being used - the "Madara DA Interface" section is a good example.

2023-10-14 09:57 UTC, DannyS03 commented on docs/exploration.md
> +## Validium Node and Validium Contracts
```suggestion
## Polygon zkEVM-based Validium

2023-10-14 09:57 UTC, DannyS03 commented on docs/exploration.md
> +## Adapter for Soverign SDK
```suggestion
## Soverign SDK Adapter 
```

2023-10-14 09:57 UTC, DannyS03 commented on docs/exploration.md
> +## OpEVM
```suggestion
## Optimistic EVM Rollup

2023-10-14 09:57 UTC, DannyS03 commented on docs/exploration.md
> +OpEVM is an EVM-compatible sovereign optimistic rollup SDK with working fraud proofs and has support for a decentralized sequencer set. OpEVM is designed for efficient and secure transaction processi
We don't mention anywhere how this is built on top of Avail and briefly how it works with Avail.

2023-10-29 23:24 UTC, merged